"""
Fara1.5 Platform SDK - Python

Official Python SDK for interacting with the Fara1.5 Browser Automation Platform.
Provides typed clients for task creation, session management, and real-time events.
"""

from .types import (
    # Enums
    ActionType,
    TaskStatus,
    SessionState,
    Priority,
    ApprovalStatus,
    SessionEventType,
    # Models
    Coordinates,
    DragCoordinates,
    ScrollDelta,
    ViewportContext,
    KeyModifiers,
    BaseAction,
    LeftClickAction,
    DoubleClickAction,
    RightClickAction,
    DragAction,
    MouseMoveAction,
    ScrollAction,
    KeyAction,
    VisitUrlAction,
    HistoryBackAction,
    ScreenshotAction,
    WaitAction,
    AskUserQuestionAction,
    TerminateAction,
    PauseAndMemorizeFactAction,
    Task,
    Session,
    ApprovalRequest,
    PaginatedResponse,
    CreateTaskInput,
    UpdateTaskInput,
    CreateSessionInput,
    ApprovalDecision,
    SessionEvent,
    StateChangedEvent,
    ActionRequestedEvent,
    ActionExecutedEvent,
    ApprovalRequiredEvent,
    ApprovalDecidedEvent,
    SessionErrorEvent,
    HeartbeatEvent,
)

from .errors import (
    FaraSDKError,
    AuthenticationError,
    TokenExpiredError,
    AuthorizationError,
    NotFoundError,
    ValidationError,
    RateLimitError,
    SessionError,
    SessionNotFoundError,
    SessionTerminatedError,
    TaskError,
    TaskNotFoundError,
    ApprovalError,
    ApprovalNotFoundError,
    ApprovalAlreadyDecidedError,
    ApprovalExpiredError,
    NetworkError,
    WebSocketError,
    WebSocketClosedError,
    TimeoutError,
    ServerError,
    BadGatewayError,
    ServiceUnavailableError,
    is_sdk_error,
    is_authentication_error,
    is_network_error,
)

from .auth import (
    TokenManager,
    AuthConfig,
    TokenResponse,
    OIDCTokens,
    OIDCDiscoveryDocument,
    fetch_oidc_discovery,
    build_authorization_url,
    exchange_code_for_tokens,
    revoke_token,
    generate_state,
    generate_code_verifier,
    generate_code_challenge,
)

from .session import (
    is_terminal_state,
    is_active_state,
    is_waiting_state,
    get_state_description,
    calculate_session_metrics,
    filter_events_by_type,
    filter_events_since,
    filter_events_until,
    SessionReplay,
    is_approval_pending,
    is_approval_expired,
    format_approval_summary,
    build_approval_decision,
    SessionLease,
    SessionMetrics,
    SESSION_STATE_DESCRIPTIONS,
)

from .client import (
    FaraClient,
    FaraClientConfig,
    create_client_with_api_key,
    create_client_with_oidc,
)

from .websocket import (
    WebSocketClient,
    WebSocketClientConfig,
    create_websocket_url,
    SessionEventIterator,
    watch_session,
)

__all__ = [
    # Types - Enums
    "ActionType",
    "TaskStatus",
    "SessionState",
    "Priority",
    "ApprovalStatus",
    "SessionEventType",
    # Types - Models
    "Coordinates",
    "DragCoordinates",
    "ScrollDelta",
    "ViewportContext",
    "KeyModifiers",
    "BaseAction",
    "LeftClickAction",
    "DoubleClickAction",
    "RightClickAction",
    "DragAction",
    "MouseMoveAction",
    "ScrollAction",
    "KeyAction",
    "VisitUrlAction",
    "HistoryBackAction",
    "ScreenshotAction",
    "WaitAction",
    "AskUserQuestionAction",
    "TerminateAction",
    "PauseAndMemorizeFactAction",
    "Task",
    "Session",
    "ApprovalRequest",
    "PaginatedResponse",
    "CreateTaskInput",
    "UpdateTaskInput",
    "CreateSessionInput",
    "ApprovalDecision",
    "SessionEvent",
    "StateChangedEvent",
    "ActionRequestedEvent",
    "ActionExecutedEvent",
    "ApprovalRequiredEvent",
    "ApprovalDecidedEvent",
    "SessionErrorEvent",
    "HeartbeatEvent",
    # Errors
    "FaraSDKError",
    "AuthenticationError",
    "TokenExpiredError",
    "AuthorizationError",
    "NotFoundError",
    "ValidationError",
    "RateLimitError",
    "SessionError",
    "SessionNotFoundError",
    "SessionTerminatedError",
    "TaskError",
    "TaskNotFoundError",
    "ApprovalError",
    "ApprovalNotFoundError",
    "ApprovalAlreadyDecidedError",
    "ApprovalExpiredError",
    "NetworkError",
    "WebSocketError",
    "WebSocketClosedError",
    "TimeoutError",
    "ServerError",
    "BadGatewayError",
    "ServiceUnavailableError",
    "is_sdk_error",
    "is_authentication_error",
    "is_network_error",
    # Auth
    "TokenManager",
    "AuthConfig",
    "TokenResponse",
    "OIDCTokens",
    "OIDCDiscoveryDocument",
    "fetch_oidc_discovery",
    "build_authorization_url",
    "exchange_code_for_tokens",
    "revoke_token",
    "generate_state",
    "generate_code_verifier",
    "generate_code_challenge",
    # Session
    "is_terminal_state",
    "is_active_state",
    "is_waiting_state",
    "get_state_description",
    "calculate_session_metrics",
    "filter_events_by_type",
    "filter_events_since",
    "filter_events_until",
    "SessionReplay",
    "is_approval_pending",
    "is_approval_expired",
    "format_approval_summary",
    "build_approval_decision",
    "SessionLease",
    "SessionMetrics",
    "SESSION_STATE_DESCRIPTIONS",
    # Client
    "FaraClient",
    "FaraClientConfig",
    "create_client_with_api_key",
    "create_client_with_oidc",
    # WebSocket
    "WebSocketClient",
    "WebSocketClientConfig",
    "create_websocket_url",
    "SessionEventIterator",
    "watch_session",
]

__version__ = "1.0.0"
