// GENERATED by demo/tools/panel_shot.py — do not edit.
//
// The run, in order, as the video plays it. `hold` is how many frames
// that state is on screen. `SPOTS` is where each callout points, measured
// off the live DOM rather than eyeballed. Regenerate with:
//
//     .venv/bin/python demo/tools/panel_shot.py

export type RunFrame = { src: string; hold: number };
export type Spot = { x: number; y: number; w: number; h: number };

export const RUN: RunFrame[] = [
  { src: "seq/00-plan.png", hold: 18 },
  { src: "seq/01-opened.png", hold: 13 },
  { src: "seq/02-step3.png", hold: 9 },
  { src: "seq/03-step5.png", hold: 8 },
  { src: "seq/04-step8.png", hold: 8 },
  { src: "seq/05-step11.png", hold: 7 },
  { src: "seq/06-working.png", hold: 11 },
  { src: "seq/07-asks.png", hold: 24 },
  { src: "seq/08-done.png", hold: 28 },
];

export const SPOTS: Record<string, Spot> = {
  plan: { x: 28, y: 271.7, w: 679.8, h: 488.8 },
  composer: { x: 0.0, y: 897.5, w: 840, h: 182.5 },
  approval: { x: 28, y: 504.6, w: 736.9, h: 361.5 },
  answer: { x: 62, y: 303.7, w: 672.9, h: 391.9 },
  deleteAll: { x: 587.4, y: 45.0, w: 144.6, h: 30.0 },
};

export const RUN_FRAMES = 126;
